class CustomException(Exception):
    pass


class AuthroizeError(CustomException):
    pass
